apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-job
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: postgres-init
          image: postgres:latest
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_DB
          command: [ "sh", "-c", "until psql -h postgres-service -U $PGUSER -d $PGDATABASE -f /config/db.sql 2>/dev/null; do sleep 1; done" ]
          volumeMounts:
            - name: config-volume
              mountPath: /config
      restartPolicy: OnFailure
      volumes:
        - name: config-volume
          configMap:
            name: postgres-config
