apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  db.sql: |
    -- Enable uuid extension
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    -- Create custom types
    CREATE TYPE vehicle_category AS ENUM ('coupe', 'suv', 'motorcycle');
    CREATE TYPE vehicle_fuel AS ENUM ('electric', 'hybrid', 'diesel', 'gas');
    CREATE TYPE vehicle_transmission AS ENUM ('manual', 'automatic');

    -- Create models table
      CREATE TABLE models (
      id UUID PRIMARY KEY,
      make VARCHAR(255) NOT NULL,
      model VARCHAR(255) NOT NULL
    );
    
    -- Create vehicles table
    CREATE TABLE vehicles (
      id UUID PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      image JSONB NOT NULL,
      video JSONB NOT NULL,
      category vehicle_category NOT NULL,
      fuel vehicle_fuel NOT NULL,
      transmission vehicle_transmission NOT NULL,
      price INT NOT NULL,
      price_monthly INT NOT NULL,
      year INT NOT NULL,
      mileage INT NOT NULL,
      horsepower INT NOT NULL,
      displacement INT NOT NULL,
      extra TEXT[] NOT NULL,
      model UUID REFERENCES models(id)
    );
    
    -- Example models
    INSERT INTO models (id, make, model) VALUES (UUID_GENERATE_V4(), 'Tesla', 'Model S');
    INSERT INTO models (id, make, model) VALUES (UUID_GENERATE_V4(), 'Ford', 'Mustang GT');
    INSERT INTO models (id, make, model) VALUES (UUID_GENERATE_V4(), 'Honda', 'CR-V');
    INSERT INTO models (id, make, model) VALUES (UUID_GENERATE_V4(), 'Harley-Davidson', 'Sportster');
    INSERT INTO models (id, make, model) VALUES (UUID_GENERATE_V4(), 'Audi', 'RS5');
    INSERT INTO models (id, make, model) VALUES (UUID_GENERATE_V4(), 'Toyota', 'RAV4 Hybrid');
    INSERT INTO models (id, make, model) VALUES (UUID_GENERATE_V4(), 'BMW', 'S1000RR');
    INSERT INTO models (id, make, model) VALUES (UUID_GENERATE_V4(), 'Porsche', 'Cayenne');
    INSERT INTO models (id, make, model) VALUES (UUID_GENERATE_V4(), 'Chevrolet', 'Corvette Stingray');
    
    -- Example vehicles
    INSERT INTO vehicles (id, title, image, video, category, fuel, transmission, price, price_monthly, year, mileage, horsepower, displacement, extra, model)
    VALUES (UUID_GENERATE_V4(), 'Tesla Model S', '{"src": "/images/Tesla-Model-S.jpeg", "alt": "Tesla Model S" }', '{ "src": "/videos/example.mp4", "alt": "Example video" }', 'coupe', 'electric', 'automatic', 80000, 1200, 2023, 0, 670, 0, '{"Piloto Automático", "Interior Premium"}', (SELECT id FROM models WHERE make='Tesla' AND model='Model S'));
    
    INSERT INTO vehicles (id, title, image, video, category, fuel, transmission, price, price_monthly, year, mileage, horsepower, displacement, extra, model)
    VALUES (UUID_GENERATE_V4(), 'Ford Mustang GT', '{"src": "/images/Ford-Mustang-GT.jpeg", "alt": "Ford Mustang GT" }', '{ "src": "/videos/example.mp4", "alt": "Example video" }', 'coupe', 'gas', 'manual', 45000, 750, 2024, 0, 450, 5038, '{"Pacote de Desempenho", "Bancos em Couro"}', (SELECT id FROM models WHERE make='Ford' AND model='Mustang GT'));
    
    INSERT INTO vehicles (id, title, image, video, category, fuel, transmission, price, price_monthly, year, mileage, horsepower, displacement, extra, model)
    VALUES (UUID_GENERATE_V4(), 'Honda CR-V', '{"src": "/images/Honda-CR-V.jpeg", "alt": "Honda CR-V" }', '{ "src": "/videos/example.mp4", "alt": "Example video" }', 'suv', 'hybrid', 'automatic', 32000, 550, 2022, 15000, 212, 1993, '{"Tração Integral", "Teto Solar"}', (SELECT id FROM models WHERE make='Honda' AND model='CR-V'));
    
    INSERT INTO vehicles (id, title, image, video, category, fuel, transmission, price, price_monthly, year, mileage, horsepower, displacement, extra, model)
    VALUES (UUID_GENERATE_V4(), 'Harley-Davidson Sportster', '{"src": "/images/Harley-Davidson-Sportster.jpeg", "alt": "Harley-Davidson Sportster" }', '{ "src": "/videos/example.mp4", "alt": "Example video" }', 'motorcycle', 'gas', 'manual', 12000, 200, 2023, 100, 60, 1202, '{"Alforges", "Para-brisas"}', (SELECT id FROM models WHERE make='Harley-Davidson' AND model='Sportster'));
    
    INSERT INTO vehicles (id, title, image, video, category, fuel, transmission, price, price_monthly, year, mileage, horsepower, displacement, extra, model)
    VALUES (UUID_GENERATE_V4(), 'Audi RS5', '{"src": "/images/Audi-RS5.jpeg", "alt": "Audi RS5" }', '{ "src": "/videos/example.mp4", "alt": "Example video" }', 'coupe', 'gas', 'automatic', 90000, 1300, 2024, 0, 450, 2894, '{}', (SELECT id FROM models WHERE make='Audi' AND model='RS5'));
    
    INSERT INTO vehicles (id, title, image, video, category, fuel, transmission, price, price_monthly, year, mileage, horsepower, displacement, extra, model)
    VALUES (UUID_GENERATE_V4(), 'Toyota RAV4 Hybrid', '{"src": "/images/Toyota-RAV4-Hybrid.jpeg", "alt": "Toyota RAV4 Hybrid" }', '{ "src": "/videos/example.mp4", "alt": "Example video" }', 'suv', 'hybrid', 'automatic', 35000, 600, 2023, 5000, 219, 2487, '{"Tração Integral", "Sistema de Navegação"}', (SELECT id FROM models WHERE make='Toyota' AND model='RAV4 Hybrid'));
    
    INSERT INTO vehicles (id, title, image, video, category, fuel, transmission, price, price_monthly, year, mileage, horsepower, displacement, extra, model)
    VALUES (UUID_GENERATE_V4(), 'BMW S1000RR', '{"src": "/images/BMW-S1000RR.jpeg", "alt": "BMW S1000RR" }', '{ "src": "/videos/example.mp4", "alt": "Example video" }', 'motorcycle', 'gas', 'manual', 18000, 300, 2024, 500, 205, 999, '{"ABS", "Sistema de Mudança Rápida"}', (SELECT id FROM models WHERE make='BMW' AND model='S1000RR'));
    
    INSERT INTO vehicles (id, title, image, video, category, fuel, transmission, price, price_monthly, year, mileage, horsepower, displacement, extra, model)
    VALUES (UUID_GENERATE_V4(), 'Porsche Cayenne', '{"src": "/images/Porsche-Cayenne.jpeg", "alt": "Porsche Cayenne" }', '{ "src": "/videos/example.mp4", "alt": "Example video" }', 'suv', 'gas', 'automatic', 70000, 1100, 2022, 20000, 335, 2995, '{"Tração Integral", "Interior em Couro"}', (SELECT id FROM models WHERE make='Porsche' AND model='Cayenne'));
    
    INSERT INTO vehicles (id, title, image, video, category, fuel, transmission, price, price_monthly, year, mileage, horsepower, displacement, extra, model)
    VALUES (UUID_GENERATE_V4(), 'Chevrolet Corvette Stingray', '{"src": "/images/Chevrolet-Corvette-Stingray.jpeg", "alt": "Chevrolet Corvette Stingray" }', '{ "src": "/videos/example.mp4", "alt": "Example video" }', 'coupe', 'gas', 'manual', 65000, 1000, 2023, 0, 490, 6162, '{"Escape de Desempenho", "Teto Targa"}', (SELECT id FROM models WHERE make='Chevrolet' AND model='Corvette Stingray'));
